# Generated by Django 3.2.4 on 2021-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=60),
        ),
    ]
